i=int(input('enter number for arthemetix:'))
j=int(input('enter second..:'))
print('i+j={}'.format(i+j))
print('i-j={}'.format(i-j))
print('i*j={}'.format(i*j))
print('i**j={} \n if you will..'.format(i**j))
print('i/2={}'.format(i/j))
print('i//2={}'.format(i//j))
print('if you will')
